# Generated by Django 5.1.1 on 2024-11-02 01:31

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_comment_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image_url",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=cloudinary_storage.storage.MediaCloudinaryStorage(),
                upload_to="images/",
            ),
        ),
    ]
